version: 1.0.11-beta {build}

branches:
  only:
  - master
  - develop

skip_tags: true

configuration:
- Debug
- Release

platform: Any CPU

environment:
  CODECOV_TOKEN:
    secure: 1253r8dPEiTvtAxdeEPP24riRPa4/7G2ivnvbB/xXi2CTu+YindCPHASfuA2PF4t
  COVERITY_TOKEN:
    secure: YVsR79t7aNYqU3qKMz+7JJuUABwSBo/X/FlCNmlnVQ0=
  COVERITY_EMAIL:
    secure: 6zUyb+IRQkAbWNWP0T0sHw==

install:
- ps: >-
    Add-Type -AssemblyName System.IO.Compression.FileSystem
      (New-Object System.Net.WebClient).DownloadFile(
        'https://github.com/dokan-dev/dokany/releases/download/v1.0.3/DokanSetup.exe',
        'C:\projects\dokancloudfs\DokanSetup.exe'
      )

cache: packages -> **\packages.config

build_script:
- cmd: >-
    nuget restore

    cov-build --dir cov-int msbuild DokanCloudFS.sln /p:UseSharedCompilation=false /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_test:
- cmd: "C:\\projects\\dokancloudfs\\DokanSetup.exe /quiet\ncopy \"C:\\Program Files\\Dokan\\Dokan Library-1.0.0\\dokan1.dll\" \"C:\\Windows\\System32\" \ncopy \"C:\\Program Files\\Dokan\\Dokan Library-1.0.0\\x86\\dokan1.dll\" \"C:\\Windows\\SysWOW64\""

test:
  categories:
    except:
    - Online
    - Manual

after_test:
- cmd: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:.\DokanCloudFS.Tests\bin\%CONFIGURATION%\IgorSoft.DokanCloudFS.Tests.dll" -filter:"+[IgorSoft.DokanCloudFS*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\DokanCloudFS_coverage.xml
    SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%
    pip install codecov
    codecov -f .\DokanCloudFS_coverage.xml -X gcov
    IF %APPVEYOR_REPO_BRANCH% NEQ master
    IF %CONFIGURATION% NEQ Debug EXIT
    7z a -r coverity.zip cov-int
    curl --form token=%COVERITY_TOKEN% --form email=%COVERITY_EMAIL% --form file=@coverity.zip --form version="1.0.11-beta" https://scan.coverity.com/builds?project=%APPVEYOR_REPO_NAME%

artifacts:
- path: coverity.zip
  name: Coverity-Upload